/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkObject *spinbutton1_adj;
  GtkWidget *spinbutton1;
  GtkWidget *label1;
  GtkWidget *button1;
  GtkWidget *button2;
  GtkWidget *scrolledwindow1;
  GtkWidget *treeview1;
  GtkWidget *skytravel;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  spinbutton1_adj = gtk_adjustment_new (1, 1, 10, 1, 10, 10);
  spinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_adj), 1, 0);
  gtk_widget_show (spinbutton1);
  gtk_fixed_put (GTK_FIXED (fixed1), spinbutton1, 256, 456);
  gtk_widget_set_size_request (spinbutton1, 60, 27);

  label1 = gtk_label_new (_("Nombres de voyageurs"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 64, 456);
  gtk_widget_set_size_request (label1, 152, 24);

  button1 = gtk_button_new_from_stock ("gtk-apply");
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 536, 528);
  gtk_widget_set_size_request (button1, 98, 32);

  button2 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed1), button2, 696, 528);
  gtk_widget_set_size_request (button2, 88, 32);
  gtk_button_set_focus_on_click (GTK_BUTTON (button2), FALSE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_fixed_put (GTK_FIXED (fixed1), scrolledwindow1, 128, 88);
  gtk_widget_set_size_request (scrolledwindow1, 496, 336);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), treeview1);

  skytravel = gtk_label_new ("");
  gtk_widget_show (skytravel);
  gtk_fixed_put (GTK_FIXED (fixed1), skytravel, 320, 24);
  gtk_widget_set_size_request (skytravel, 144, 24);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, spinbutton1, "spinbutton1");
  GLADE_HOOKUP_OBJECT (window1, label1, "label1");
  GLADE_HOOKUP_OBJECT (window1, button1, "button1");
  GLADE_HOOKUP_OBJECT (window1, button2, "button2");
  GLADE_HOOKUP_OBJECT (window1, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (window1, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (window1, skytravel, "skytravel");

  return window1;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed2;
  GtkObject *jr_adj;
  GtkWidget *jr;
  GtkObject *ms_adj;
  GtkWidget *ms;
  GtkObject *an_adj;
  GtkWidget *an;
  GtkObject *jr1_adj;
  GtkWidget *jr1;
  GtkObject *ms1_adj;
  GtkWidget *ms1;
  GtkObject *an1_adj;
  GtkWidget *an1;
  GtkWidget *dd;
  GtkWidget *aa;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *classe;
  GtkWidget *prix;
  GtkWidget *label3;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label2;
  GtkWidget *Retour0;
  GtkWidget *image3;
  GtkWidget *label15;
  GtkWidget *afficher;
  GtkWidget *appliquer;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label17;
  GtkWidget *quitter;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label18;
  GtkWidget *label26;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (window2), fixed2);

  jr_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jr = gtk_spin_button_new (GTK_ADJUSTMENT (jr_adj), 1, 0);
  gtk_widget_show (jr);
  gtk_fixed_put (GTK_FIXED (fixed2), jr, 176, 112);
  gtk_widget_set_size_request (jr, 60, 27);

  ms_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  ms = gtk_spin_button_new (GTK_ADJUSTMENT (ms_adj), 1, 0);
  gtk_widget_show (ms);
  gtk_fixed_put (GTK_FIXED (fixed2), ms, 312, 112);
  gtk_widget_set_size_request (ms, 60, 27);

  an_adj = gtk_adjustment_new (1, 2019, 2020, 1, 10, 10);
  an = gtk_spin_button_new (GTK_ADJUSTMENT (an_adj), 1, 0);
  gtk_widget_show (an);
  gtk_fixed_put (GTK_FIXED (fixed2), an, 440, 112);
  gtk_widget_set_size_request (an, 60, 27);

  jr1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jr1 = gtk_spin_button_new (GTK_ADJUSTMENT (jr1_adj), 1, 0);
  gtk_widget_show (jr1);
  gtk_fixed_put (GTK_FIXED (fixed2), jr1, 176, 184);
  gtk_widget_set_size_request (jr1, 60, 27);

  ms1_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  ms1 = gtk_spin_button_new (GTK_ADJUSTMENT (ms1_adj), 1, 0);
  gtk_widget_show (ms1);
  gtk_fixed_put (GTK_FIXED (fixed2), ms1, 320, 184);
  gtk_widget_set_size_request (ms1, 60, 27);

  an1_adj = gtk_adjustment_new (2019, 2019, 2020, 1, 10, 10);
  an1 = gtk_spin_button_new (GTK_ADJUSTMENT (an1_adj), 1, 0);
  gtk_widget_show (an1);
  gtk_fixed_put (GTK_FIXED (fixed2), an1, 448, 184);
  gtk_widget_set_size_request (an1, 60, 27);

  dd = gtk_entry_new ();
  gtk_widget_show (dd);
  gtk_fixed_put (GTK_FIXED (fixed2), dd, 144, 40);
  gtk_widget_set_size_request (dd, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (dd), 8226);

  aa = gtk_entry_new ();
  gtk_widget_show (aa);
  gtk_fixed_put (GTK_FIXED (fixed2), aa, 472, 40);
  gtk_widget_set_size_request (aa, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (aa), 8226);

  label8 = gtk_label_new (_("jours"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 184, 88);
  gtk_widget_set_size_request (label8, 41, 17);

  label9 = gtk_label_new (_("mois"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 312, 88);
  gtk_widget_set_size_request (label9, 41, 17);

  label10 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 440, 80);
  gtk_widget_set_size_request (label10, 64, 24);

  label11 = gtk_label_new (_("jours"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 176, 152);
  gtk_widget_set_size_request (label11, 49, 17);

  label12 = gtk_label_new (_("mois"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 320, 160);
  gtk_widget_set_size_request (label12, 49, 17);

  label13 = gtk_label_new (_("ann\303\251e"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 448, 160);
  gtk_widget_set_size_request (label13, 49, 17);

  label14 = gtk_label_new (_("Classe"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 64, 320);
  gtk_widget_set_size_request (label14, 49, 17);

  classe = gtk_combo_box_new_text ();
  gtk_widget_show (classe);
  gtk_fixed_put (GTK_FIXED (fixed2), classe, 192, 312);
  gtk_widget_set_size_request (classe, 192, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (classe), _("Economique"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (classe), _("Premi\303\250re"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (classe), _("classe affaire"));

  prix = gtk_entry_new ();
  gtk_widget_show (prix);
  gtk_fixed_put (GTK_FIXED (fixed2), prix, 200, 240);
  gtk_widget_set_size_request (prix, 112, 24);
  gtk_entry_set_invisible_char (GTK_ENTRY (prix), 8226);

  label3 = gtk_label_new (_("Arriv\303\251e \303\240"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed2), label3, 336, 40);
  gtk_widget_set_size_request (label3, 80, 24);

  label4 = gtk_label_new (_("Date de depart "));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed2), label4, 40, 112);
  gtk_widget_set_size_request (label4, 112, 24);

  label5 = gtk_label_new (_("Date d'arriv\303\251e"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed2), label5, 40, 184);
  gtk_widget_set_size_request (label5, 104, 24);

  label2 = gtk_label_new (_("Depart de"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed2), label2, 40, 40);
  gtk_widget_set_size_request (label2, 72, 24);

  Retour0 = gtk_button_new ();
  gtk_widget_show (Retour0);
  gtk_fixed_put (GTK_FIXED (fixed2), Retour0, 24, 8);
  gtk_widget_set_size_request (Retour0, 66, 29);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_container_add (GTK_CONTAINER (Retour0), image3);

  label15 = gtk_label_new (_("Prix"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed2), label15, 64, 248);
  gtk_widget_set_size_request (label15, 56, 24);

  afficher = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (afficher);
  gtk_fixed_put (GTK_FIXED (fixed2), afficher, 88, 384);
  gtk_widget_set_size_request (afficher, 104, 32);

  appliquer = gtk_button_new ();
  gtk_widget_show (appliquer);
  gtk_fixed_put (GTK_FIXED (fixed2), appliquer, 256, 376);
  gtk_widget_set_size_request (appliquer, 104, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (appliquer), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic ("Appliquer");
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox1), label17, FALSE, FALSE, 0);

  quitter = gtk_button_new ();
  gtk_widget_show (quitter);
  gtk_fixed_put (GTK_FIXED (fixed2), quitter, 488, 376);
  gtk_widget_set_size_request (quitter, 88, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (quitter), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic ("Quitter");
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox2), label18, FALSE, FALSE, 0);

  label26 = gtk_label_new (_("<span foreground=\"blue\"size=\"xx-large\"><i><b> SKY TRAVEL </b></i></span>"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed2), label26, 288, 8);
  gtk_widget_set_size_request (label26, 184, 24);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  g_signal_connect ((gpointer) Retour0, "clicked",
                    G_CALLBACK (on_Retour0_clicked),
                    NULL);
  g_signal_connect ((gpointer) afficher, "clicked",
                    G_CALLBACK (on_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) appliquer, "clicked",
                    G_CALLBACK (on_appliquer_clicked),
                    NULL);
  g_signal_connect ((gpointer) quitter, "clicked",
                    G_CALLBACK (on_quitter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (window2, jr, "jr");
  GLADE_HOOKUP_OBJECT (window2, ms, "ms");
  GLADE_HOOKUP_OBJECT (window2, an, "an");
  GLADE_HOOKUP_OBJECT (window2, jr1, "jr1");
  GLADE_HOOKUP_OBJECT (window2, ms1, "ms1");
  GLADE_HOOKUP_OBJECT (window2, an1, "an1");
  GLADE_HOOKUP_OBJECT (window2, dd, "dd");
  GLADE_HOOKUP_OBJECT (window2, aa, "aa");
  GLADE_HOOKUP_OBJECT (window2, label8, "label8");
  GLADE_HOOKUP_OBJECT (window2, label9, "label9");
  GLADE_HOOKUP_OBJECT (window2, label10, "label10");
  GLADE_HOOKUP_OBJECT (window2, label11, "label11");
  GLADE_HOOKUP_OBJECT (window2, label12, "label12");
  GLADE_HOOKUP_OBJECT (window2, label13, "label13");
  GLADE_HOOKUP_OBJECT (window2, label14, "label14");
  GLADE_HOOKUP_OBJECT (window2, classe, "classe");
  GLADE_HOOKUP_OBJECT (window2, prix, "prix");
  GLADE_HOOKUP_OBJECT (window2, label3, "label3");
  GLADE_HOOKUP_OBJECT (window2, label4, "label4");
  GLADE_HOOKUP_OBJECT (window2, label5, "label5");
  GLADE_HOOKUP_OBJECT (window2, label2, "label2");
  GLADE_HOOKUP_OBJECT (window2, Retour0, "Retour0");
  GLADE_HOOKUP_OBJECT (window2, image3, "image3");
  GLADE_HOOKUP_OBJECT (window2, label15, "label15");
  GLADE_HOOKUP_OBJECT (window2, afficher, "afficher");
  GLADE_HOOKUP_OBJECT (window2, appliquer, "appliquer");
  GLADE_HOOKUP_OBJECT (window2, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (window2, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (window2, image1, "image1");
  GLADE_HOOKUP_OBJECT (window2, label17, "label17");
  GLADE_HOOKUP_OBJECT (window2, quitter, "quitter");
  GLADE_HOOKUP_OBJECT (window2, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window2, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (window2, image2, "image2");
  GLADE_HOOKUP_OBJECT (window2, label18, "label18");
  GLADE_HOOKUP_OBJECT (window2, label26, "label26");

  return window2;
}

GtkWidget*
create_window3 (void)
{
  GtkWidget *window3;
  GtkWidget *fixed3;
  GtkWidget *scrolledwindow2;
  GtkWidget *affich;
  GtkWidget *retour_aj;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image7;
  GtkWidget *label24;
  GtkWidget *supp;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image8;
  GtkWidget *label25;
  GtkWidget *Modifier0;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image6;
  GtkWidget *label23;

  window3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window3), _("window3"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (window3), fixed3);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow2);
  gtk_fixed_put (GTK_FIXED (fixed3), scrolledwindow2, 8, 16);
  gtk_widget_set_size_request (scrolledwindow2, 520, 312);

  affich = gtk_tree_view_new ();
  gtk_widget_show (affich);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), affich);

  retour_aj = gtk_button_new ();
  gtk_widget_show (retour_aj);
  gtk_fixed_put (GTK_FIXED (fixed3), retour_aj, 392, 368);
  gtk_widget_set_size_request (retour_aj, 80, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (retour_aj), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox5), image7, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox5), label24, FALSE, FALSE, 0);

  supp = gtk_button_new ();
  gtk_widget_show (supp);
  gtk_fixed_put (GTK_FIXED (fixed3), supp, 88, 368);
  gtk_widget_set_size_request (supp, 120, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (supp), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image8 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox6), image8, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("suppression"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox6), label25, FALSE, FALSE, 0);

  Modifier0 = gtk_button_new ();
  gtk_widget_show (Modifier0);
  gtk_fixed_put (GTK_FIXED (fixed3), Modifier0, 248, 368);
  gtk_widget_set_size_request (Modifier0, 96, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (Modifier0), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image6 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox4), image6, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox4), label23, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) affich, "row_activated",
                    G_CALLBACK (on_affich_row_activated),
                    NULL);
  g_signal_connect ((gpointer) retour_aj, "clicked",
                    G_CALLBACK (on_retour_aj_clicked),
                    NULL);
  g_signal_connect ((gpointer) supp, "clicked",
                    G_CALLBACK (on_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) Modifier0, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window3, window3, "window3");
  GLADE_HOOKUP_OBJECT (window3, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (window3, scrolledwindow2, "scrolledwindow2");
  GLADE_HOOKUP_OBJECT (window3, affich, "affich");
  GLADE_HOOKUP_OBJECT (window3, retour_aj, "retour_aj");
  GLADE_HOOKUP_OBJECT (window3, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window3, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (window3, image7, "image7");
  GLADE_HOOKUP_OBJECT (window3, label24, "label24");
  GLADE_HOOKUP_OBJECT (window3, supp, "supp");
  GLADE_HOOKUP_OBJECT (window3, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (window3, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (window3, image8, "image8");
  GLADE_HOOKUP_OBJECT (window3, label25, "label25");
  GLADE_HOOKUP_OBJECT (window3, Modifier0, "Modifier0");
  GLADE_HOOKUP_OBJECT (window3, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window3, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (window3, image6, "image6");
  GLADE_HOOKUP_OBJECT (window3, label23, "label23");

  return window3;
}

GtkWidget*
create_window4 (void)
{
  GtkWidget *window4;
  GtkWidget *fixed4;
  GtkWidget *SKY_TRAVEL;
  GtkWidget *gestionvol;
  GtkWidget *gestionexcurtion;

  window4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window4), _("window4"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (window4), fixed4);

  SKY_TRAVEL = gtk_label_new (_("SKY TRAVEL"));
  gtk_widget_show (SKY_TRAVEL);
  gtk_fixed_put (GTK_FIXED (fixed4), SKY_TRAVEL, 120, 24);
  gtk_widget_set_size_request (SKY_TRAVEL, 168, 24);

  gestionvol = gtk_button_new_with_mnemonic (_("Gestion des vols"));
  gtk_widget_show (gestionvol);
  gtk_fixed_put (GTK_FIXED (fixed4), gestionvol, 120, 88);
  gtk_widget_set_size_request (gestionvol, 168, 56);

  gestionexcurtion = gtk_button_new_with_mnemonic (_("Gestion des excurtions"));
  gtk_widget_show (gestionexcurtion);
  gtk_fixed_put (GTK_FIXED (fixed4), gestionexcurtion, 120, 168);
  gtk_widget_set_size_request (gestionexcurtion, 168, 56);

  g_signal_connect ((gpointer) gestionvol, "clicked",
                    G_CALLBACK (on_gestionvol_clicked),
                    NULL);
  g_signal_connect ((gpointer) gestionexcurtion, "clicked",
                    G_CALLBACK (on_gestionexcurtion_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window4, window4, "window4");
  GLADE_HOOKUP_OBJECT (window4, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (window4, SKY_TRAVEL, "SKY_TRAVEL");
  GLADE_HOOKUP_OBJECT (window4, gestionvol, "gestionvol");
  GLADE_HOOKUP_OBJECT (window4, gestionexcurtion, "gestionexcurtion");

  return window4;
}

GtkWidget*
create_window5 (void)
{
  GtkWidget *window5;
  GtkWidget *fixed5;
  GtkWidget *Return3;
  GtkWidget *image4;
  GtkWidget *Arriv__e___;
  GtkWidget *D__part_de_;
  GtkWidget *Prix;
  GtkWidget *entry1;
  GtkWidget *entry2;
  GtkWidget *entry3;
  GtkWidget *SKY_TRAVEL;
  GtkWidget *Valider0;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image5;
  GtkWidget *label22;
  GtkWidget *image9;

  window5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window5), _("window5"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (window5), fixed5);
  gtk_widget_set_size_request (fixed5, 500, 400);

  Return3 = gtk_button_new ();
  gtk_widget_show (Return3);
  gtk_fixed_put (GTK_FIXED (fixed5), Return3, 48, 16);
  gtk_widget_set_size_request (Return3, 66, 29);

  image4 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_container_add (GTK_CONTAINER (Return3), image4);

  Arriv__e___ = gtk_label_new (_("Arriv\303\251e \303\240 "));
  gtk_widget_show (Arriv__e___);
  gtk_fixed_put (GTK_FIXED (fixed5), Arriv__e___, 56, 104);
  gtk_widget_set_size_request (Arriv__e___, 49, 17);

  D__part_de_ = gtk_label_new (_("D\303\251part de "));
  gtk_widget_show (D__part_de_);
  gtk_fixed_put (GTK_FIXED (fixed5), D__part_de_, 16, 152);
  gtk_widget_set_size_request (D__part_de_, 136, 24);

  Prix = gtk_label_new (_("Prix"));
  gtk_widget_show (Prix);
  gtk_fixed_put (GTK_FIXED (fixed5), Prix, 40, 208);
  gtk_widget_set_size_request (Prix, 88, 32);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed5), entry1, 176, 72);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  entry2 = gtk_entry_new ();
  gtk_widget_show (entry2);
  gtk_fixed_put (GTK_FIXED (fixed5), entry2, 176, 120);
  gtk_widget_set_size_request (entry2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2), 8226);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed5), entry3, 176, 200);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  SKY_TRAVEL = gtk_label_new (_("SKY TAVEL"));
  gtk_widget_show (SKY_TRAVEL);
  gtk_fixed_put (GTK_FIXED (fixed5), SKY_TRAVEL, 296, 16);
  gtk_widget_set_size_request (SKY_TRAVEL, 88, 32);

  Valider0 = gtk_button_new ();
  gtk_widget_show (Valider0);
  gtk_fixed_put (GTK_FIXED (fixed5), Valider0, 24, 328);
  gtk_widget_set_size_request (Valider0, 120, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (Valider0), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image5 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox3), image5, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox3), label22, FALSE, FALSE, 0);

  image9 = create_pixmap (window5, "vol0.jpeg");
  gtk_widget_show (image9);
  gtk_fixed_put (GTK_FIXED (fixed5), image9, 152, 56);
  gtk_widget_set_size_request (image9, 415, 207);

  g_signal_connect ((gpointer) Return3, "clicked",
                    G_CALLBACK (on_Return3_clicked),
                    NULL);
  g_signal_connect ((gpointer) Valider0, "clicked",
                    G_CALLBACK (on_Valider0_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window5, window5, "window5");
  GLADE_HOOKUP_OBJECT (window5, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (window5, Return3, "Return3");
  GLADE_HOOKUP_OBJECT (window5, image4, "image4");
  GLADE_HOOKUP_OBJECT (window5, Arriv__e___, "Arriv__e___");
  GLADE_HOOKUP_OBJECT (window5, D__part_de_, "D__part_de_");
  GLADE_HOOKUP_OBJECT (window5, Prix, "Prix");
  GLADE_HOOKUP_OBJECT (window5, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window5, entry2, "entry2");
  GLADE_HOOKUP_OBJECT (window5, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (window5, SKY_TRAVEL, "SKY_TRAVEL");
  GLADE_HOOKUP_OBJECT (window5, Valider0, "Valider0");
  GLADE_HOOKUP_OBJECT (window5, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window5, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (window5, image5, "image5");
  GLADE_HOOKUP_OBJECT (window5, label22, "label22");
  GLADE_HOOKUP_OBJECT (window5, image9, "image9");

  return window5;
}

